lesson 19: rack
popeskul/rack-app pull request #1
Opened 2021-07-07 10:25 UTC by popeskul

В отдельном резпозитории напишите минималистичное Rack приложение которое будет отвечать на  
URL GET /time
с параметром строки запроса format и возвращать время в заданном формате. 

Например, GET-запрос  
/time?format=year%2Cmonth%2Cday
вернет ответ с типом text/plain и телом 1970-01-01.

Доступные форматы времени: year, month, day, hour, minute, second
Форматы передаются в параметре строки запроса format в любом порядке
Если среди форматов времени присутствует неизвестный формат, необходимо возвращать ответ с кодом статуса 400 и телом "Unknown time format [epoch]"
Если неизвестных форматов несколько, все они должны быть перечислены в теле ответа, например: "Unknown time format [epoch, age]"
При запросе на любой другой URL необходимо возвращать ответ с кодом статуса 404

Ответ к заданию должен быть в виде открытого пулл-реквеста.

2021-07-07 18:52 UTC, BubuntuClu requested changes

2021-07-07 18:52 UTC, BubuntuClu commented on services/time_converter.rb
> +    @format.map { |t| Time.now.send(t) }.join("-")
ты на каждый параметр вызываешь метод Time.now.send, что не очень хорошо. собери строку из ключей для  функции `strftime` и за одни раз конвертацию сделай

2021-07-07 18:52 UTC, BubuntuClu commented on services/time_converter.rb
> +  ACCEPTABLE_FORMAT = %w(year month day hour minute second)
сделай тут хэш, где ключ это слово времени, а занчение ключ для `strftime`

2021-07-07 18:52 UTC, BubuntuClu commented on middleware/time_formatter.rb
> +    @request = Rack::Request.new(env)
зачем это сделано переменной инстанса?

2021-07-07 18:52 UTC, BubuntuClu commented on middleware/time_formatter.rb
> +  def handle_time_request
передай явно параметр `request_params`, тогда она тоже не нужна будет как переменная инстанса, а будет обычной

2021-07-07 18:52 UTC, BubuntuClu commented on services/time_converter.rb
> +    if acceptably?
ты сначала в классе приложения вызываешь эту проверку, потом когда вызываешь строку, о5 проверяешь. два раза гоняешь вычитание массивов. а если строка неудачная то и три раза.
сделай метод `call` который за один обход массива соберет тебе строку с правильными параметрами(можно сразу ключи для strfrime) и строку с ошибочными параметрами. в методе `success?/acceptably?` проверишь массив ошибок пустой ли? и потом два отдельных метода на успешную строку и на ошибочную строку

2021-07-07 18:52 UTC, BubuntuClu commented on middleware/time_formatter.rb
> +    if @request.path == TIME_URL
поменяй тут порядок проверок чтобы можно было избавиться от вложенного ифа

2021-07-07 20:25 UTC, popeskul commented on services/time_converter.rb
> +    @format.map { |t| Time.now.send(t) }.join("-")
Исправил через strftime

2021-07-07 20:25 UTC, popeskul commented on services/time_converter.rb
> +  ACCEPTABLE_FORMAT = %w(year month day hour minute second)
Поправил

2021-07-07 20:49 UTC, popeskul commented on services/time_converter.rb
> +    if acceptably?
Поправил

2021-07-07 20:50 UTC, popeskul commented on middleware/time_formatter.rb
> +    @request = Rack::Request.new(env)
Верно, поправил

2021-07-07 20:51 UTC, popeskul commented on middleware/time_formatter.rb
> +  def handle_time_request
Хороший план

2021-07-07 20:56 UTC, popeskul commented on middleware/time_formatter.rb
> +    if @request.path == TIME_URL
Поменял проверки

2021-07-08 07:34 UTC, BubuntuClu approved these changes

2021-07-08 07:34 UTC, BubuntuClu commented on middleware/time_formatter.rb
> +    time_formatter = TimeConverter.new(user_format)
```
time_formatter = TimeConverter.new(user_format)
time_formatter.call
if time_formatter.success?
  final_response(STATUS[:success], headers, "#{time_formatter.time_string}")
else
  final_response(STATUS[:error], headers, "#{time_formatter.invalid_string}")
end
```

чего-то такого ожидал

метод `call` должен делать какую-то логику, в нашем случае заполнять два массива параметров.
у тебя немного напутано по порядку методов

2021-07-08 07:34 UTC, BubuntuClu commented on services/time_converter.rb
> +    if valid_params?
```
@format.each do |f|
      if ACCEPTABLE_FORMAT.key?(f)
        @valid_formats << ACCEPTABLE_FORMAT[f]
      else
        @wrong_formats << f
      end
```

такой вариант мне больше нравится

2021-07-08 08:38 UTC, popeskul commented on services/time_converter.rb
> +    if valid_params?
Поправил

2021-07-08 08:39 UTC, merged